Repository vmware-tanzu/kubeapps, pull requests merged in 2022-11, with the labels that each got.

#5590 Migrate prerelease flow to GHA
  .github/workflows/kubeapps-full-integration.yaml
  .github/workflows/kubeapps-main-reusable.yaml
  .github/workflows/kubeapps.yaml
Labels: component/ci, github_actions, cla-not-required

#5605 Remove "isLoaded" flag from deployment form
  dashboard/src/components/DeploymentForm/DeploymentFormBody/DeploymentFormBody.tsx
Labels: cla-not-required

#5602 Autofix typos
  cmd/apprepository-controller/server/controller.go
  cmd/apprepository-controller/server/controller_test.go
  cmd/asset-syncer/server/delete.go
  cmd/asset-syncer/server/utils.go
  cmd/kubeapps-apis/core/plugins/v1alpha1/plugins.go
  cmd/kubeapps-apis/docs/kubeapps-apis.swagger.json
  cmd/kubeapps-apis/gen/core/packages/v1alpha1/packages.pb.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/OCI_TERMINOLOGY.md
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/cache/watcher_cache.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/chart_integration_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/common/transport/transport.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/docker_reg_v2_repo_lister.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/global_vars_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/oci_repo.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/release.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/release_integration_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo_integration_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/testdata/ghcr-util.sh
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/testdata/registry-app.yaml
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/utils/fake/chart.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/utils/postgresql_utils.go
  cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_ctrl_packages.go
  cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_data_adapters.go
  cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go
  cmd/kubeapps-apis/proto/kubeappsapis/core/packages/v1alpha1/packages.proto
  cmd/kubeapps-apis/server/server.go
  cmd/pinniped-proxy/src/https.rs
  dashboard/public/openapi.yaml
  dashboard/src/actions/availablepackages.ts
  dashboard/src/components/AppView/AccessURLTable/AccessURLItem/AccessURLIngressHelper.test.ts
  dashboard/src/components/AppView/AccessURLTable/AccessURLItem/AccessURLIngressHelper.tsx
  dashboard/src/components/Catalog/PackageCatalogItem.tsx
  dashboard/src/components/Config/PkgRepoList/PkgRepoForm.tsx
  dashboard/src/components/ErrorBoundary/ErrorBoundary.test.tsx
  dashboard/src/components/OperatorInstanceFormBody/OperatorInstanceFormBody.test.tsx
  dashboard/src/components/SelectRepoForm/SelectRepoForm.tsx
  dashboard/src/containers/Root.test.tsx
  dashboard/src/gen/kubeappsapis/core/packages/v1alpha1/packages.ts
  dashboard/src/shared/KubeappsGrpcClient.test.ts
  dashboard/src/shared/yamlUtils.ts
  pkg/helm/index.go
  pkg/http-client/httpclient_test.go
  script/chart-template-test.sh
  script/install-nginx.sh
  site/content/docs/latest/background/update-api-docs.md
  site/content/docs/latest/howto/OIDC/OAuth2OIDC-azure-active-directory.md
  site/content/docs/latest/howto/dashboard.md
  site/content/docs/latest/reference/proposals/authentication-and-authorization.md
  site/content/docs/latest/reference/proposals/replacing-mongodb.md
  site/content/docs/latest/reference/scripts/setup-harbor.sh
  site/content/docs/latest/reference/scripts/setup-kubeapps.sh
  site/content/docs/latest/tutorials/managing-carvel-packages.md
  site/content/docs/latest/tutorials/managing-flux-packages.md
  site/content/docs/latest/tutorials/managing-package-repositories.md
  site/content/docs/latest/tutorials/operators.md
  site/data/docs/latest-toc.yml
  site/themes/template/assets/scss/_footer.scss
Labels: cla-not-required

#5610 Regenerate `openapi.yaml` file
  dashboard/public/openapi.yaml
  site/content/docs/latest/reference/developer/release-process.md
Labels: cla-not-required

#5584 Part of the fix for a flux app in failed install state, deleted via UX, stays around in k8s flux HelmRelease CR #5577
  chart/kubeapps/README.md
  chart/kubeapps/values.yaml
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/common/utils.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/common/utils_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/global_vars_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/integration_utils_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/release.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/release_integration_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/release_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo_integration_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/server.go
  script/e2e-test.sh
  script/makefiles/deploy-dev.mk
Labels: cla-not-required

#5586 Fix license headers
  .github/workflows/add-issues-to-project.yaml
  .github/workflows/codeql-reusable.yml
  .github/workflows/kubeapps-general.yaml
  .licenserc.yaml
  dashboard/public/browserconfig.xml
  site/themes/template/static/img/favicons/browserconfig.xml
Labels: cla-not-required

#5607 Fix wrong indentation in release-process.md
  site/content/docs/latest/reference/developer/release-process.md
Labels: kind/enhancement, cla-not-required

#5613 Increase timeout for local_e2e_tests(opeartor) to avoid flaky tests
  .github/workflows/kubeapps-general.yaml
Labels: component/ci, kind/enhancement, github_actions, cla-not-required

#5617 Rename GHA's `main` job to `CI`
  .github/workflows/kubeapps-full-integration.yaml
  .github/workflows/kubeapps-main.yaml
  .github/workflows/kubeapps-release.yml
Labels: component/ci, kind/enhancement, github_actions, cla-not-required

#5618 Adjust concurrency in gha workflow
  .github/workflows/kubeapps-main.yaml
  .github/workflows/kubeapps-release.yml
Labels: component/ci, github_actions, cla-not-required

#5620 Add status badges for GHA's workflows
  README.md
Labels: component/ci, kind/enhancement, github_actions, cla-not-required

#5621 Run GHA's Full Integration Pipeline on schedule
  .github/workflows/kubeapps-full-integration.yaml
Labels: component/ci, kind/enhancement, github_actions, cla-not-required

#5626 Fix flux e2e test
  integration/tests/flux/04-default-deployment.spec.js
Labels: component/plugin-flux, cla-not-required

#5619 Trigger GHA release workflow on tags following `test-*` pattern
  .github/workflows/kubeapps-general.yaml
  .github/workflows/kubeapps-release.yml
Labels: component/ci, github_actions, cla-not-required

#5629 Extract codeql from GHA linters
  .github/workflows/codeql-analysis.yml
  .github/workflows/codeql-scheduled.yml
  .github/workflows/linters.yml
Labels: component/ci, github_actions, cla-not-required

#5628 Add status check jobs for local_e2e_tests matrix and linters
  .github/workflows/kubeapps-general.yaml
Labels: component/ci, kind/enhancement, github_actions, cla-not-required

#5632 Add SRP source provenance report
  .github/actions/srp-source-provenance/action.yml
  .github/workflows/kubeapps-general.yaml
Labels: component/ci, github_actions, cla-not-required

#5636 Add makefile lint target
  .licenserc.yaml
  .yamllint.yml
  Makefile
  script/linters/golang-linter.sh
  script/linters/license-linter.sh
  script/linters/yaml-linter.sh
Labels: kind/enhancement, cla-not-required

#5639 Call chekout action before using srp-source-provenance
  .github/workflows/kubeapps-general.yaml
Labels: component/ci, github_actions, cla-not-required

#5647 Fix srp_report GHA's job
  .github/workflows/kubeapps-general.yaml
Labels: component/ci, github_actions, cla-not-required

#5604 Package repository permissions endpoint
  cmd/kubeapps-apis/core/packages/v1alpha1/repositories.go
  cmd/kubeapps-apis/core/packages/v1alpha1/repositories_test.go
  cmd/kubeapps-apis/core/plugins/v1alpha1/plugins.go
  cmd/kubeapps-apis/docs/kubeapps-apis.swagger.json
  cmd/kubeapps-apis/gen/core/packages/v1alpha1/packages.pb.gw.go
  cmd/kubeapps-apis/gen/core/packages/v1alpha1/repositories.pb.go
  cmd/kubeapps-apis/gen/core/packages/v1alpha1/repositories.pb.gw.go
  cmd/kubeapps-apis/gen/core/packages/v1alpha1/repositories_grpc.pb.go
  cmd/kubeapps-apis/gen/core/plugins/v1alpha1/plugins.pb.gw.go
  cmd/kubeapps-apis/gen/plugins/fluxv2/packages/v1alpha1/fluxv2.pb.go
  cmd/kubeapps-apis/gen/plugins/fluxv2/packages/v1alpha1/fluxv2.pb.gw.go
  cmd/kubeapps-apis/gen/plugins/fluxv2/packages/v1alpha1/fluxv2_grpc.pb.go
  cmd/kubeapps-apis/gen/plugins/helm/packages/v1alpha1/helm.pb.go
  cmd/kubeapps-apis/gen/plugins/helm/packages/v1alpha1/helm.pb.gw.go
  cmd/kubeapps-apis/gen/plugins/helm/packages/v1alpha1/helm_grpc.pb.go
  cmd/kubeapps-apis/gen/plugins/kapp_controller/packages/v1alpha1/kapp_controller.pb.go
  cmd/kubeapps-apis/gen/plugins/kapp_controller/packages/v1alpha1/kapp_controller.pb.gw.go
  cmd/kubeapps-apis/gen/plugins/kapp_controller/packages/v1alpha1/kapp_controller_grpc.pb.go
  cmd/kubeapps-apis/gen/plugins/resources/v1alpha1/resources.pb.gw.go
  cmd/kubeapps-apis/plugin_test/mock_plugin.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/server.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/server_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/test_util_test.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_test.go
  cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_ctrl_repositories.go
  cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go
  cmd/kubeapps-apis/plugins/pkg/resources/resources_access.go
  cmd/kubeapps-apis/proto/kubeappsapis/core/packages/v1alpha1/repositories.proto
  cmd/kubeapps-apis/proto/kubeappsapis/plugins/fluxv2/packages/v1alpha1/fluxv2.proto
  cmd/kubeapps-apis/proto/kubeappsapis/plugins/helm/packages/v1alpha1/helm.proto
  cmd/kubeapps-apis/proto/kubeappsapis/plugins/kapp_controller/packages/v1alpha1/kapp_controller.proto
  dashboard/public/openapi.yaml
  dashboard/src/gen/kubeappsapis/core/packages/v1alpha1/repositories.ts
  dashboard/src/gen/kubeappsapis/plugins/fluxv2/packages/v1alpha1/fluxv2.ts
  dashboard/src/gen/kubeappsapis/plugins/helm/packages/v1alpha1/helm.ts
  dashboard/src/gen/kubeappsapis/plugins/kapp_controller/packages/v1alpha1/kapp_controller.ts
Labels: cla-not-required

#5608 Package repository UI adapted based on repository permissions API
  dashboard/src/actions/repos.test.tsx
  dashboard/src/actions/repos.ts
  dashboard/src/components/Catalog/Catalog.test.tsx
  dashboard/src/components/Config/PkgRepoList/PkgRepoList.test.tsx
  dashboard/src/components/Config/PkgRepoList/PkgRepoList.tsx
  dashboard/src/reducers/repos.test.ts
  dashboard/src/reducers/repos.ts
  dashboard/src/shared/PackageRepositoriesService.test.ts
  dashboard/src/shared/PackageRepositoriesService.ts
  dashboard/src/shared/types.ts
Labels: cla-not-required

#5649 Fix typo in srp command
  .github/actions/srp-source-provenance/action.yml
Labels: component/ci, github_actions, cla-not-required

#5627 Remove js-yaml dependency
  dashboard/package.json
  dashboard/src/components/AppView/AppView.tsx
  dashboard/src/components/OperatorInstance/OperatorInstance.tsx
  dashboard/src/components/OperatorInstanceForm/OperatorInstanceForm.test.tsx
  dashboard/src/components/OperatorInstanceForm/OperatorInstanceForm.tsx
  dashboard/src/components/OperatorInstanceFormBody/OperatorInstanceFormBody.test.tsx
  dashboard/src/components/OperatorInstanceFormBody/OperatorInstanceFormBody.tsx
  dashboard/src/components/OperatorInstanceUpdateForm/OperatorInstanceUpdateForm.test.tsx
  dashboard/src/components/OperatorInstanceUpdateForm/OperatorInstanceUpdateForm.tsx
  dashboard/src/components/UpgradeForm/UpgradeForm.tsx
  dashboard/src/shared/schema.ts
  dashboard/src/shared/yamlUtils.ts
  dashboard/yarn.lock
Labels: cla-not-required

#5612 removed use of UserManagedSecrets flag for helm plugin repos (issue4870)
  chart/kubeapps/README.md
  chart/kubeapps/values.yaml
  cmd/kubeapps-apis/docs/kubeapps-apis.swagger.json
  cmd/kubeapps-apis/gen/apidocs.pb.go
  cmd/kubeapps-apis/gen/core/packages/v1alpha1/packages.pb.go
  cmd/kubeapps-apis/gen/core/packages/v1alpha1/packages.pb.gw.go
  cmd/kubeapps-apis/gen/core/packages/v1alpha1/repositories.pb.go
  cmd/kubeapps-apis/gen/core/packages/v1alpha1/repositories.pb.gw.go
  cmd/kubeapps-apis/gen/core/plugins/v1alpha1/plugins.pb.go
  cmd/kubeapps-apis/gen/core/plugins/v1alpha1/plugins.pb.gw.go
  cmd/kubeapps-apis/gen/plugins/fluxv2/packages/v1alpha1/fluxv2.pb.go
  cmd/kubeapps-apis/gen/plugins/fluxv2/packages/v1alpha1/fluxv2.pb.gw.go
  cmd/kubeapps-apis/gen/plugins/helm/packages/v1alpha1/helm.pb.go
  cmd/kubeapps-apis/gen/plugins/helm/packages/v1alpha1/helm.pb.gw.go
  cmd/kubeapps-apis/gen/plugins/helm/packages/v1alpha1/helm_grpc.pb.go
  cmd/kubeapps-apis/gen/plugins/kapp_controller/packages/v1alpha1/kapp_controller.pb.go
  cmd/kubeapps-apis/gen/plugins/kapp_controller/packages/v1alpha1/kapp_controller.pb.gw.go
  cmd/kubeapps-apis/gen/plugins/resources/v1alpha1/resources.pb.go
  cmd/kubeapps-apis/gen/plugins/resources/v1alpha1/resources.pb.gw.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/common/plugin.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_auth.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_test.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go
  cmd/kubeapps-apis/proto/kubeappsapis/plugins/helm/packages/v1alpha1/helm.proto
  dashboard/src/gen/kubeappsapis/plugins/helm/packages/v1alpha1/helm.ts
Labels: cla-not-required

#5657 Update deprecated parameter in the call to srp tool
  .github/actions/srp-source-provenance/action.yml
Labels: component/ci, github_actions, cla-not-required

#5658 Update Kubeapps maintainers team
  MAINTAINERS.md
  site/content/contributors/3-agamez.md
  site/content/contributors/3-gfichtenholtz.md
  site/content/contributors/4-dlaloue.md
  site/content/contributors/5-rcastelblanque.md
  site/content/contributors/7-jbenito.md
  site/themes/template/static/img/team/agamez.png
  site/themes/template/static/img/team/jbenito.png
  site/themes/template/static/img/team/rcastelblanque.png
Labels: cla-not-required

#5550 Re-enable hash tests after unsuccessfully trying to repro.
  cmd/pinniped-proxy/Cargo.lock
  cmd/pinniped-proxy/Cargo.toml
  cmd/pinniped-proxy/src/pinniped.rs
Labels: cla-not-required

#5576 Switch cache to custom without write-lock for reads.
  chart/kubeapps/templates/frontend/deployment.yaml
  cmd/pinniped-proxy/Cargo.lock
  cmd/pinniped-proxy/Cargo.toml
  cmd/pinniped-proxy/src/cache.rs
  cmd/pinniped-proxy/src/https.rs
  cmd/pinniped-proxy/src/main.rs
  cmd/pinniped-proxy/src/pinniped.rs
  cmd/pinniped-proxy/src/service.rs
Labels: cla-not-required

#5656 Run flux e2e test group in GHA's local_e2e_tests job
  .github/workflows/kubeapps-general.yaml
  script/e2e-test.sh
  script/lib/libtest.sh
Labels: component/ci, github_actions, cla-not-required

#5668 fix an unintended change to a file done in my previous PR
  .github/workflows/kubeapps-general.yaml
Labels: cla-not-required

#5664 Issue5542 - Unable to edit or delete newly created flux package repository
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/global_vars_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo.go
  cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_ctrl_repositories.go
  cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_data_resources.go
  cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go
  dashboard/src/components/Config/PkgRepoList/PkgRepoForm.tsx
  dashboard/src/shared/utils.test.ts
  dashboard/src/shared/utils.ts
Labels: cla-not-required

#5583 Call the offending `get_client_config` only when required.
  cmd/pinniped-proxy/src/pinniped.rs
  cmd/pinniped-proxy/src/service.rs
Labels: cla-not-required

#5644 fix for flux plugin: clean up old charts from chart cache after repo update #4115
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/cache/chart_cache.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/chart.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/chart_integration_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/chart_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/global_vars_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/oci_repo.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/release_integration_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/release_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo_integration_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/server_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/test_util_test.go
Labels: cla-not-required

#5685 Add some minor improvements in the GHA's kubeapps-general pipeline
  .github/workflows/kubeapps-general.yaml
Labels: component/ci, github_actions, cla-not-required

#5623 Merge user values with defaults before validation.
  dashboard/src/actions/installedpackages.ts
  dashboard/src/shared/schema.test.ts
  dashboard/src/shared/schema.ts
Labels: cla-not-required

#5693 Fix wrong regex for testing the release in GHA
  .github/workflows/kubeapps-release.yml
Labels: component/ci, github_actions, cla-not-required

#5694 Fix GHA's release workflow
  .github/workflows/kubeapps-general.yaml
Labels: component/ci, github_actions, cla-not-required

#5673 issue4870 - refactor helm to use managed-by annotation
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_auth.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_test.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/test_util_test.go
Labels: cla-not-required

#5715 bump flux version used in tests to latest available
  script/e2e-test.sh
  script/makefiles/deploy-dev.mk
Labels: cla-not-required

#5718 Simplify release-related logic in GHA's kubeapps general pipeline
  .github/workflows/kubeapps-general.yaml
  .github/workflows/kubeapps-release.yml
  script/create_release.sh
Labels: component/ci, github_actions, cla-not-required

#5714 fix for [Repository] refactor fluxv2 to use managed-by annotation instead of system flag #4871
  chart/kubeapps/README.md
  chart/kubeapps/values.yaml
  cmd/kubeapps-apis/docs/kubeapps-apis.swagger.json
  cmd/kubeapps-apis/gen/plugins/fluxv2/packages/v1alpha1/fluxv2.pb.go
  cmd/kubeapps-apis/gen/plugins/fluxv2/packages/v1alpha1/fluxv2.pb.gw.go
  cmd/kubeapps-apis/gen/plugins/fluxv2/packages/v1alpha1/fluxv2_grpc.pb.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/chart_integration_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/common/utils.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/global_vars_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/integration_utils_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/release_integration_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo_auth.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo_integration_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/server.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/test_util_test.go
  cmd/kubeapps-apis/proto/kubeappsapis/plugins/fluxv2/packages/v1alpha1/fluxv2.proto
  dashboard/src/gen/kubeappsapis/plugins/fluxv2/packages/v1alpha1/fluxv2.ts
Labels: cla-not-required

#5702 Extract custom default values from package tarball
  cmd/kubeapps-apis/docs/kubeapps-apis.swagger.json
  cmd/kubeapps-apis/gen/core/packages/v1alpha1/packages.pb.go
  cmd/kubeapps-apis/proto/kubeappsapis/core/packages/v1alpha1/packages.proto
  dashboard/src/actions/availablepackages.test.tsx
  dashboard/src/components/PackageHeader/PackageHeader.test.tsx
  dashboard/src/components/PackageHeader/PackageView.test.tsx
  dashboard/src/gen/kubeappsapis/core/packages/v1alpha1/packages.ts
  pkg/chart/models/chart.go
  pkg/tarutil/tarutil.go
  pkg/tarutil/tarutil_test.go
  pkg/tarutil/test/utils.go
Labels: cla-not-required

#5704 Simple rename.
  cmd/asset-syncer/server/postgresql_utils_test.go
  cmd/asset-syncer/server/utils.go
  cmd/asset-syncer/server/utils_test.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go
  pkg/chart/models/chart.go
Labels: cla-not-required

#5730 Decommission circleci
  .circleci.bak/config.yml
  .github/workflows/gke_e2e_tests.yaml
  .github/workflows/kubeapps-general.yaml
  .github/workflows/kubeapps-release.yml
  chart/kubeapps/README.md
  script/chart_sync.sh
  script/chart_sync_utils.sh
  script/chart_upstream_checker.sh
  script/create_release.sh
  script/lib/libcitools.sh
  script/start-gke-env.sh
Labels: component/ci, github_actions, cla-not-required

#5712 Update CI docs
  .github/workflows/ci-custodian-rules.yaml
  chart/kubeapps/README.md
  site/content/docs/latest/img/ci-workflow-main.png
  site/content/docs/latest/img/ci-workflow-release.png
  site/content/docs/latest/reference/developer/release-process.md
  site/content/docs/latest/reference/testing/ci.md
  site/content/docs/latest/reference/testing/end-to-end-tests.md
  site/data/docs/latest-toc.yml
Labels: component/ci, github_actions, cla-not-required

#5760 Remove the CircleCI badge
  README.md
Labels: component/ci, github_actions

#5695 Improve wording to avoid implying pinniped is used either way.
  site/content/docs/latest/tutorials/using-an-OIDC-provider.md
Labels: cla-not-required
