Repository vmware-tanzu/kubeapps, pull requests merged in 2022-10, with the labels that each got.

#5419 Fix circleci pipeline
  .circleci/config.yml
Labels: cla-not-required

#5425 Add new adopters logo: SAP
  ADOPTERS.md
  site/content/docs/latest/img/adopters/sap.jpg
  site/content/docs/latest/img/adopters/sap.svg
Labels: cla-not-required

#5384 Add new CICD workflow in Github Actions
  .circleci/config.yml
  .github/workflows/kubeapps.yaml
  script/chart_sync.sh
  script/chart_sync_utils.sh
  script/chart_upstream_checker.sh
  script/create-additional-kind-cluster.sh
  script/create-kind-cluster.sh
  script/e2e-test.sh
  script/install-multicluster-deps.sh
  script/lib/libcitools.sh
  script/lib/libtest.sh
Labels: cla-not-required

#5428 Fix for GKE CI pipeline
  .circleci/config.yml
  script/chart-museum.sh
  script/e2e-test.sh
  script/install-nginx.sh
Labels: cla-not-required

#5417 Update dashboard how-to guide
  site/content/docs/latest/howto/README.md
  site/content/docs/latest/howto/dashboard.md
  site/content/docs/latest/img/dashboard/browse-application-parameters.png
  site/content/docs/latest/img/dashboard/browse-application.png
  site/content/docs/latest/img/dashboard/browse-catalog.png
  site/content/docs/latest/img/dashboard/delete-application.png
  site/content/docs/latest/img/dashboard/deploy-application-progress-0.png
  site/content/docs/latest/img/dashboard/deploy-application-progress-1.png
  site/content/docs/latest/img/dashboard/deploy-application-progress-ready.png
  site/content/docs/latest/img/dashboard/deploy-application-visual-editor-parameters.png
  site/content/docs/latest/img/dashboard/deploy-application-visual-editor.png
  site/content/docs/latest/img/dashboard/deploy-application-yaml-editor.png
  site/content/docs/latest/img/dashboard/list-available-applications.png
  site/content/docs/latest/img/dashboard/update-application-list.png
  site/content/docs/latest/img/dashboard/update-application-message.png
  site/content/docs/latest/img/dashboard/update-application-visual-editor.png
  site/content/docs/latest/img/dashboard/update-application-yaml-editor.png
  site/content/docs/latest/img/mariadb-chart.png
  site/content/docs/latest/img/mariadb-deployment.png
  site/content/docs/latest/img/mariadb-installation.png
Labels: cla-not-required

#5424 Add Flux auth provider option to UI
  dashboard/src/components/Config/PkgRepoList/PkgRepoForm.test.tsx
  dashboard/src/components/Config/PkgRepoList/PkgRepoForm.tsx
  dashboard/src/reducers/repos.ts
  dashboard/src/shared/PackageRepositoriesService.ts
  dashboard/src/shared/types.ts
Labels: cla-not-required

#5431 Fix the job push_dev_images from GHA workflow
  .github/workflows/kubeapps.yaml
Labels: cla-not-required

#5429 Run GHA pipeline on pushes to main branch
  .github/workflows/kubeapps.yaml
Labels: cla-not-required

#5430 Change IMG_MODIFIER suffix for the GHA workflow
  .github/workflows/kubeapps.yaml
Labels: component/ci, cla-not-required

#5441 Fix push_images job from GH Actions workflow
  .github/workflows/kubeapps.yaml
Labels: kind/bug, component/ci, cla-not-required

#5433 Update access control how-to guide
  site/content/docs/latest/howto/access-control.md
Labels: cla-not-required

#5444 Search table nested params
  dashboard/src/components/DeploymentForm/DeploymentFormBody/BasicDeploymentForm/TabularSchemaEditorTable/TabularSchemaEditorTable.tsx
  dashboard/src/components/DeploymentForm/DeploymentFormBody/BasicDeploymentForm/TabularSchemaEditorTable/TabularSchemaEditorTableHelpers.ts
Labels: cla-not-required

#5449 [CI,GKE] Use `gke-gcloud-auth-plugin` for `kubectl` auth
  .circleci/config.yml
Labels: cla-not-required

#5451 Optimize CI pipeline
  .github/workflows/kubeapps.yaml
  script/e2e-test.sh
  script/run_e2e_tests.sh
Labels: cla-not-required

#5465 Skip non-image files when loading docker images in local_e2e_tests
  .github/workflows/kubeapps.yaml
Labels: kind/bug, component/ci, github_actions, cla-not-required

#5464 Use GitHub Actions' environment file for steps' outputs
  .github/workflows/kubeapps.yaml
Labels: component/ci, kind/enhancement, security, github_actions, cla-not-required

#5438 Fix codeql issue
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/OCI_TERMINOLOGY.md
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/harbor_api_v2_repo_lister.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/testdata/gcloud-setup.md
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/testdata/harbor-create-project.json
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/testdata/harbor-create-robot-account.json
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/testdata/cert/ca-config.json
Labels: cla-not-required

#5456 Fix a11y-related issues on the website
  site/config.yaml
  site/content/community/_index.html
  site/content/resources/_index.html
  site/themes/template/assets/scss/_base.scss
  site/themes/template/assets/scss/_components.scss
  site/themes/template/assets/scss/_footer.scss
  site/themes/template/assets/scss/_header.scss
  site/themes/template/assets/scss/_mixins.scss
  site/themes/template/assets/scss/_variables.scss
  site/themes/template/layouts/404.html
  site/themes/template/layouts/_default/_markup/render-heading.html
  site/themes/template/layouts/_default/_markup/render-image.html
  site/themes/template/layouts/_default/_markup/render-link.html
  site/themes/template/layouts/_default/baseof.html
  site/themes/template/layouts/_default/docs.html
  site/themes/template/layouts/_default/list.html
  site/themes/template/layouts/_default/plugins.html
  site/themes/template/layouts/_default/posts.html
  site/themes/template/layouts/_default/search.html
  site/themes/template/layouts/_default/section.html
  site/themes/template/layouts/_default/single.html
  site/themes/template/layouts/_default/summary.html
  site/themes/template/layouts/_default/tag.html
  site/themes/template/layouts/_default/versions.html
  site/themes/template/layouts/index.html
  site/themes/template/layouts/partials/base-footer.html
  site/themes/template/layouts/partials/base-getting-started.html
  site/themes/template/layouts/partials/base-header.html
  site/themes/template/layouts/partials/blog-post-card.html
  site/themes/template/layouts/partials/docs-right-bar.html
  site/themes/template/layouts/partials/docs-sidebar.html
  site/themes/template/layouts/partials/home-contributors.html
  site/themes/template/layouts/partials/home-grey-block.html
  site/themes/template/layouts/partials/home-hero.html
  site/themes/template/layouts/partials/pagination.html
  site/themes/template/layouts/partials/plugins.html
  site/themes/template/layouts/partials/use-cases.html
  site/themes/template/layouts/shortcodes/resource-item.html
  site/themes/template/layouts/shortcodes/youtube.html
Labels: cla-not-required

#5461 [Dashboard] Fix for error flashing when deleting repo
  dashboard/src/components/Config/PkgRepoList/PkgRepoControl.test.tsx
  dashboard/src/components/Config/PkgRepoList/PkgRepoControl.tsx
Labels: cla-not-required

#5466 Repos global list on additional clusters
  dashboard/src/actions/repos.ts
  dashboard/src/components/Config/PkgRepoList/PkgRepoList.tsx
Labels: cla-not-required

#5455 Update Hugo version
  script/makefiles/site.mk
  site/content/docs/latest/reference/developer/release-process.md
  site/netlify.toml
Labels: cla-not-required

#5469 Rename bitnami/charts's branch to master to main
  .circleci/config.yml
  .github/workflows/kubeapps.yaml
  CONTRIBUTING.md
  README.md
  chart/kubeapps/README.md
  chart/kubeapps/values.yaml
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/cache/chart_cache.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/global_vars_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/testdata/charts/airflow-many-versions.yaml
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/testdata/charts/index-with-categories.yaml
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/testdata/charts/redis-14.3.4.tgz
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/testdata/charts/redis-14.4.0.tgz
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/testdata/charts/redis-many-versions.yaml
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/testdata/charts/redis-two-versions.yaml
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/testdata/charts/single-package-template.yaml
  script/chart_sync_utils.sh
  script/tpl/PR_external_chart_template.md
  script/tpl/PR_internal_chart_template.md
  site/content/docs/latest/howto/OIDC/OAuth2OIDC-keycloak.md
  site/content/docs/latest/howto/basic-form-support.md
  site/content/docs/latest/howto/custom-app-view-support.md
  site/content/docs/latest/howto/offline-installation.md
  site/content/docs/latest/howto/private-app-repository.md
  site/content/docs/latest/reference/developer/kubeapps-apis.md
  site/content/docs/latest/reference/developer/release-process.md
  site/content/docs/latest/reference/testing/ci.md
  site/content/docs/latest/tutorials/getting-started.md
  site/content/docs/latest/tutorials/kubeapps-on-tce/03-preparing-kubeapps-deployment.md
  site/content/docs/latest/tutorials/kubeapps-on-tkg/step-2.md
Labels: cla-not-required

#5442 Remove unused code + refactor after Kubeops removal
  cmd/apprepository-controller/server/controller.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/common/utils.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/server.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_auth.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_validation.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_validation_test.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/utils/chart-client.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/utils/chart-client_test.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/utils/fake/chart.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/utils/testdata/nginx-5.1.1-apiVersionV1.tgz
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/utils/testdata/nginx-5.1.1-apiVersionV2.tgz
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/utils/utils.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/utils/utils_test.go
  cmd/kubeapps-apis/plugins/pkg/helm/agent/agent.go
  cmd/kubeapps-apis/plugins/pkg/helm/agent/agent_test.go
  cmd/kubeapps-apis/plugins/pkg/helm/agent/docker_secrets_postrenderer.go
  cmd/kubeapps-apis/plugins/pkg/helm/agent/docker_secrets_postrenderer_test.go
  cmd/kubeapps-apis/plugins/pkg/helm/agent/httpConfigForCluster.go
  cmd/kubeapps-apis/plugins/pkg/helm/helmaction_configgetter.go
  cmd/kubeapps-apis/plugins/pkg/resourcerefs/resourcerefs.go
  pkg/chart/chart.go
  pkg/chart/chart_test.go
  pkg/helm/chartclient.go
  pkg/helm/chartclient_test.go
  pkg/helm/secrets.go
  pkg/http-client/httpclient.go
  pkg/http-client/httpclient_test.go
  pkg/kube/cluster_config.go
  pkg/kube/cluster_config_test.go
  pkg/kube/fake.go
  pkg/kube/kube_handler.go
  pkg/kube/kube_handler_test.go
  pkg/kube/kube_utils.go
  pkg/kube/kube_utils_test.go
Labels: cla-not-required

#5453 [Helm plugin] Fix for listing repos without cluster-wide permissions
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/main.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_test.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go
  cmd/kubeapps-apis/plugins/pkg/resources/namespaces.go
  cmd/kubeapps-apis/plugins/pkg/resources/namespaces_test.go
  cmd/kubeapps-apis/plugins/resources/v1alpha1/namespaces_filtering.go
Labels: cla-not-required

#5460 [Carvel plugin] Fix for listing repos without cluster-wide permissions
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go
  cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/main.go
  cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server.go
  cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_ctrl_repositories.go
  cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_data_resources.go
  cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go
  cmd/kubeapps-apis/plugins/pkg/resources/namespaces.go
Labels: cla-not-required

#5454 Small changes to check Carvel multicluster support.
  cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_data_adapters.go
  script/makefiles/deploy-dev.mk
  site/content/docs/latest/tutorials/managing-carvel-packages.md
Labels: cla-not-required

#5445 [pinniped-proxy] Update from structopt to clapv4. Fixes #5357
  cmd/pinniped-proxy/Cargo.lock
  cmd/pinniped-proxy/Cargo.toml
  cmd/pinniped-proxy/src/cli.rs
  cmd/pinniped-proxy/src/main.rs
  cmd/pinniped-proxy/tests/cli_tests.rs
  cmd/pinniped-proxy/tests/cmd/help.trycmd
Labels: cla-not-required

#5504 [Helm plugin] Remove unnecessary context check
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go
Labels: cla-not-required

#5509 Add flag for disabling dashboard
  chart/kubeapps/Chart.yaml
  chart/kubeapps/README.md
  chart/kubeapps/templates/dashboard/configmap.yaml
  chart/kubeapps/templates/dashboard/deployment.yaml
  chart/kubeapps/templates/dashboard/service.yaml
  chart/kubeapps/templates/frontend/configmap.yaml
  chart/kubeapps/values.yaml
Labels: cla-not-required

#5480 Package repository management UI for users with restricted permissions
  dashboard/src/components/Config/PkgRepoList/PkgRepoDisabledControl.tsx
  dashboard/src/components/Config/PkgRepoList/PkgRepoList.test.tsx
  dashboard/src/components/Config/PkgRepoList/PkgRepoList.tsx
  dashboard/src/shared/PackageRepositoriesService.ts
  dashboard/src/shared/types.ts
Labels: cla-not-required

#5497 Update OIDC with pinniped guide to comply with style guidelines
  site/content/docs/latest/tutorials/using-an-OIDC-provider.md
Labels: cla-not-required

#5524 Fix the jobs sync from/to bitnami in the GHA's "kubeapps general" workflow
  .circleci/config.yml
  .github/workflows/kubeapps.yaml
  script/chart_sync.sh
  script/chart_sync_utils.sh
  script/chart_upstream_checker.sh
Labels: component/ci, github_actions, cla-not-required

#5531 Yaml decoding fix
  dashboard/src/shared/yamlUtils.ts
Labels: cla-not-required

#5534 Add remaining schema renderers
  dashboard/src/components/DeploymentForm/DeploymentFormBody/BasicDeploymentForm/TabularSchemaEditorTable/Params/ArrayParam.tsx
  dashboard/src/components/DeploymentForm/DeploymentFormBody/BasicDeploymentForm/TabularSchemaEditorTable/Params/BooleanParam.tsx
  dashboard/src/components/DeploymentForm/DeploymentFormBody/BasicDeploymentForm/TabularSchemaEditorTable/Params/TextParam.tsx
  dashboard/src/components/DeploymentForm/DeploymentFormBody/BasicDeploymentForm/TabularSchemaEditorTable/TabularSchemaEditorTableRenderer.tsx
  dashboard/src/shared/utils.ts
Labels: cla-not-required

#5533 Consistent json schema validation of SliderParams
  dashboard/src/components/DeploymentForm/DeploymentFormBody/BasicDeploymentForm/TabularSchemaEditorTable/Params/ArrayParam.tsx
  dashboard/src/components/DeploymentForm/DeploymentFormBody/BasicDeploymentForm/TabularSchemaEditorTable/Params/BooleanParam.tsx
  dashboard/src/components/DeploymentForm/DeploymentFormBody/BasicDeploymentForm/TabularSchemaEditorTable/Params/SliderParam.tsx
  dashboard/src/components/DeploymentForm/DeploymentFormBody/BasicDeploymentForm/TabularSchemaEditorTable/Params/TextParam.tsx
  dashboard/src/components/DeploymentForm/DeploymentFormBody/BasicDeploymentForm/TabularSchemaEditorTable/TabularSchemaEditorTableRenderer.tsx
  dashboard/src/shared/utils.ts
Labels: cla-not-required

#5549 Fixes for Optimize OCI repository lister lookups in flux plugin #5523 and Unable to delete Flux package in "pending" state #5538
  cmd/kubeapps-apis/core/packages/v1alpha1/packages.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/cache/rate_limiting_queue.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/cache/watcher_cache.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/chart.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/chart_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/docker_reg_v2_repo_lister.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/global_vars_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/harbor_api_v2_repo_lister.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/oci_repo.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/oci_repo_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/release.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/release_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo_integration_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo_test.go
  cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/server.go
Labels: component/plugin-flux, cla-not-required

#5554 Add multicluster design proposal
  site/content/docs/latest/reference/proposals/README.md
Labels: cla-not-required

#5518 Remove sync_writes optino for pinniped-proxy cred cache.
  cmd/pinniped-proxy/Cargo.lock
  cmd/pinniped-proxy/Cargo.toml
  cmd/pinniped-proxy/src/main.rs
  cmd/pinniped-proxy/src/pinniped.rs
  script/makefiles/deploy-dev-for-pinniped.mk
  site/content/docs/latest/howto/OIDC/using-an-OIDC-provider-with-pinniped.md
  site/content/docs/latest/reference/developer/pinniped-proxy.md
Labels: cla-not-required

#5564 SchemaEditor behind a feature flag
  chart/kubeapps/Chart.yaml
  chart/kubeapps/README.md
  chart/kubeapps/values.yaml
  dashboard/public/config.json
  dashboard/src/actions/config.test.tsx
  dashboard/src/components/AppList/AppList.test.tsx
  dashboard/src/components/AppView/AppControls/DeleteButton/DeleteButton.test.tsx
  dashboard/src/components/AppView/AppControls/RollbackButton/RollbackButton.test.tsx
  dashboard/src/components/AppView/AppControls/UpgradeButton/UpgradeButton.test.tsx
  dashboard/src/components/AppView/CustomAppView/CustomAppView.test.tsx
  dashboard/src/components/Catalog/Catalog.test.tsx
  dashboard/src/components/Config/PkgRepoList/PkgRepoButton.test.tsx
  dashboard/src/components/Config/PkgRepoList/PkgRepoControl.test.tsx
  dashboard/src/components/Config/PkgRepoList/PkgRepoForm.test.tsx
  dashboard/src/components/Config/PkgRepoList/PkgRepoList.test.tsx
  dashboard/src/components/DeploymentForm/DeploymentFormBody/BasicDeploymentForm/TabularSchemaEditorTable/Params/CustomFormParam.test.tsx
  dashboard/src/components/DeploymentForm/DeploymentFormBody/DeploymentFormBody.test.tsx
  dashboard/src/components/DeploymentForm/DeploymentFormBody/DeploymentFormBody.tsx
  dashboard/src/components/Header/ContextSelector.test.tsx
  dashboard/src/components/Header/Menu.test.tsx
  dashboard/src/components/Layout/Layout.test.tsx
  dashboard/src/components/OperatorInstance/OperatorInstance.test.tsx
  dashboard/src/components/OperatorInstanceForm/OperatorInstanceForm.test.tsx
  dashboard/src/components/OperatorInstanceUpdateForm/OperatorInstanceUpdateForm.test.tsx
  dashboard/src/components/OperatorList/OperatorList.test.tsx
  dashboard/src/components/OperatorNew/OperatorNew.test.tsx
  dashboard/src/components/OperatorView/OperatorView.test.tsx
  dashboard/src/components/PackageHeader/PackageReadme.test.tsx
  dashboard/src/components/PackageHeader/PackageView.test.tsx
  dashboard/src/components/SelectRepoForm/SelectRepoForm.test.tsx
  dashboard/src/containers/LoginFormContainer/LoginFormContainer.test.tsx
  dashboard/src/containers/RoutesContainer/Routes.test.tsx
  dashboard/src/reducers/cluster.test.ts
  dashboard/src/reducers/config.ts
  dashboard/src/shared/Auth.test.ts
  dashboard/src/shared/Config.ts
Labels: cla-not-required

#5543 Add Kubeapps setup for headless (API-only mode)
  chart/kubeapps/Chart.yaml
  chart/kubeapps/README.md
  chart/kubeapps/templates/ingress-api.yaml
  chart/kubeapps/templates/ingress.yaml
  chart/kubeapps/values.yaml
  script/makefiles/cluster-kind.mk
  site/content/docs/latest/reference/manifests/kubeapps-local-dev-additional-apiserver-config.yaml
Labels: cla-not-required

#5566 Add explicit token for Kubeapps cluster reference
  cmd/kubeapps-apis/core/plugins/v1alpha1/plugins.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go
  pkg/kube/cluster_config.go
  pkg/kube/cluster_config_test.go
Labels: cla-not-required

#5567 Update deps
  .circleci/config.yml
  .github/workflows/kubeapps.yaml
  cmd/apprepository-controller/Dockerfile
  cmd/asset-syncer/Dockerfile
  cmd/asset-syncer/server/postgresql_db_test.go
  cmd/kubeapps-apis/Dockerfile
  cmd/kubeapps-apis/buf.lock
  cmd/kubeapps-apis/gen/core/packages/v1alpha1/packages.pb.go
  cmd/kubeapps-apis/gen/core/packages/v1alpha1/repositories.pb.go
  cmd/kubeapps-apis/gen/plugins/fluxv2/packages/v1alpha1/fluxv2.pb.go
  cmd/kubeapps-apis/gen/plugins/fluxv2/packages/v1alpha1/fluxv2.pb.gw.go
  cmd/kubeapps-apis/gen/plugins/helm/packages/v1alpha1/helm.pb.go
  cmd/kubeapps-apis/gen/plugins/helm/packages/v1alpha1/helm.pb.gw.go
  cmd/kubeapps-apis/gen/plugins/kapp_controller/packages/v1alpha1/kapp_controller.pb.go
  cmd/kubeapps-apis/gen/plugins/kapp_controller/packages/v1alpha1/kapp_controller.pb.gw.go
  cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/utils/postgres_db_test.go
  cmd/pinniped-proxy/Cargo.lock
  dashboard/Dockerfile
  dashboard/package.json
  dashboard/src/gen/protoc-gen-openapiv2/options/openapiv2.ts
  dashboard/yarn.lock
  go.mod
  go.sum
  integration/Dockerfile
  integration/yarn.lock
  script/chart-museum.sh
  script/e2e-test.sh
  site/content/docs/latest/reference/developer/release-process.md
Labels: cla-not-required

#5535 Avoid requiring SA in Flux plugin in the UI
  dashboard/src/components/DeploymentForm/DeploymentForm.tsx
  dashboard/src/shared/utils.test.ts
  dashboard/src/shared/utils.ts
Labels: cla-not-required

#5578 Fix website meta tags issues
  site/archetypes/default.md
  site/netlify.toml
  site/themes/template/layouts/_default/baseof.html
  site/themes/template/layouts/_default/plugins.html
  site/themes/template/layouts/_default/posts.html
  site/themes/template/layouts/_default/tag.html
  site/themes/template/layouts/partials/blog-post-card.html
  site/themes/template/layouts/partials/pagination.html
  site/themes/template/layouts/partials/plugins.html
Labels: cla-not-required

#5587 Fix website search issue
  site/themes/template/layouts/_default/baseof.html
  site/themes/template/layouts/_default/search.html
  site/themes/template/static/js/main.js
Labels: cla-not-required

#5582 Migrate GKE jobs to GitHub Actions
  .circleci/config.yml
  .github/workflows/add-issues-to-project.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/gke_e2e_tests.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/kubeapps.yaml
  .github/workflows/license-headers.yaml
  script/chart-museum.sh
  script/e2e-test.sh
  script/lib/libcitools.sh
  script/local-docker-registry.sh
  script/run_e2e_tests.sh
  script/start-gke-env.sh
Labels: component/ci, github_actions, cla-not-required
